### ISSUE TITLE
Logo Proposal for LoFi Monkey Ball

### ISSUE THREAD

**Issue by area55git** [eschirtz/LoFi-MonkeyBall#1]
Hi @eschirtz, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project LoFi Monkey Ball.
You can use it in your game and in your Youtube Channel as well
I will be pleased to collaborate with you.

**Comment by eschirtz** [comment]
Hey @area55git! Thank you for reaching out. I am actually no longer developing this application. However, If you want to take a look at my "Threads" repo, it could be cool to have some graphics made for the landing page. I'm working on some myself right now, but if you want to collaborate I'm sure we could do something! Check out the current (non-production) version [here](https://thread-spinner.firebaseapp.com/#/newscene)

**Comment by area55git** [comment]
I'm going to start designing the sketches for thread.
